language: php

services:
    - docker

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

php:
    - 7.0
    - 7.1

sudo: false

install:
    - travis_retry composer install

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
    - sudo service mysql stop
    - docker-compose -f ./tests/docker-compose.yml up -d
    - php tests/wait.php
    - php tests/setup-schema.php

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - docker-compose -f ./tests/docker-compose.yml down
    - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
